---
    - name: enable epel repository
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    - name: enable epel repository
      shell: yum-config-manager --enable epel
    - name: enable epel repository
      shell: yum repolist