---
    - name: "Ensure MariaDB is started"
      service:
        name: mariadb
        state: started
    
    - name: "Create database user"
      mysql_user:
        name: "{{db_user}}"
        password: "{{db_password}}"
        priv: '*.*:ALL'
        host: '%'
        state: present
    - name: "Add database"
      mysql_db:
        name: "{{db_name}}"
        state: present