---
    - name: Create influxdb datasource
      grafana_datasource:
        name: "{{datasource_name}}"
        grafana_url: "http://127.0.0.1:8080"
        grafana_user: "admin"
        grafana_password: "admin"
        org_id: "1"
        ds_type: "influxdb"
        url: "http://localhost:8086"
        database: "{{metrics_database_name}}"
        password: "{{metrics_database_password}}"
        user: "{{metrics_database_user}}"