---
- name: "Install Grafana"
  yum:
    name: "{{grafana_url}}"
    state: present
- name: "Copy Grafana config"
  template:
    src: files/grafana.ini
    dest: /etc/grafana/grafana.ini
- name: "Start Grafana"
  service:
    name: "grafana-server"
    state: restarted